kind: pipeline
name: concourse-helm-resource

steps:

- name: build_concourse-helm-resource
  image: cycognito/drone-docker-builder:latest
  settings:
    image: cycognito/concourse-helm-resource
    username: cycognito
    password:
      from_secret: docker_password
    dockerfile: Dockerfile
  volumes:
  - name: docker
    path: /var/run/


volumes:
- name: docker
  host:
    path: /var/run









